# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a00d6f76682b61d97a6e1ece4de756566aafae8a4f7c3f0c15aea543ab2d335caa387525fb1f5d57448d18e923ab67867ecb75448f58bea71c621dfb68a57e0

test:
  secret_key_base: 68fe80fd7148273c55aa81fe1b80532cf59c620bf8888c1830247e8e6941b479d77e6fe1b93b54b0657b0a158eff77c27846e0f1e961e61badb5c6cfa3122ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
